"""Repository protocol interfaces (abstract contracts)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import uuid

    from odg_core.audit import AuditEvent
    from odg_core.enums import AuditEventType, DecisionStatus
    from odg_core.models import ApprovalRecord, GovernanceDecision, RACIAssignment, VetoRecord


class DecisionRepository(Protocol):
    async def create(self, decision: GovernanceDecision) -> GovernanceDecision: ...
    async def get_by_id(self, decision_id: uuid.UUID) -> GovernanceDecision | None: ...
    async def update(self, decision: GovernanceDecision) -> GovernanceDecision: ...
    async def list_decisions(
        self,
        *,
        domain_id: str | None = None,
        status: DecisionStatus | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[GovernanceDecision]: ...


class ApprovalRepository(Protocol):
    async def create(self, record: ApprovalRecord) -> ApprovalRecord: ...
    async def get_vote(self, decision_id: uuid.UUID, voter_id: str) -> ApprovalRecord | None: ...
    async def list_by_decision(self, decision_id: uuid.UUID) -> list[ApprovalRecord]: ...


class VetoRepository(Protocol):
    async def create(self, veto: VetoRecord) -> VetoRecord: ...
    async def get_by_id(self, veto_id: uuid.UUID) -> VetoRecord | None: ...
    async def update(self, veto: VetoRecord) -> VetoRecord: ...
    async def list_by_decision(self, decision_id: uuid.UUID) -> list[VetoRecord]: ...


class AuditRepository(Protocol):
    async def create(self, event: AuditEvent) -> AuditEvent: ...
    async def get_last_hash(self) -> str | None: ...
    async def get_chain(self, *, limit: int = 1000) -> list[AuditEvent]: ...
    async def list_by_entity(self, entity_id: str, *, limit: int = 50) -> list[AuditEvent]: ...
    async def list_events(
        self,
        *,
        event_type: AuditEventType | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[AuditEvent]: ...


class RACIRepository(Protocol):
    async def create(self, assignment: RACIAssignment) -> RACIAssignment: ...
    async def get_by_id(self, assignment_id: uuid.UUID) -> RACIAssignment | None: ...
    async def get_assignment(self, user_id: str, domain_id: str) -> RACIAssignment | None: ...
    async def delete(self, assignment_id: uuid.UUID) -> None: ...
    async def list_by_domain(self, domain_id: str) -> list[RACIAssignment]: ...
    async def list_by_user(self, user_id: str) -> list[RACIAssignment]: ...
